-- =============================================================================
-- Migration: 0001_create_users_table.sql
-- Tool: Goose
-- Direction: Up creates, Down drops
--
-- Schema: auth
-- Table: auth.users — stores Data Principals (citizens) and Data Fiduciaries
-- =============================================================================

-- +goose Up
-- +goose StatementBegin

CREATE TABLE IF NOT EXISTS auth.users (
    -- Primary key: UUID v4, generated by the application
    id          UUID            PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Who this user is (citizen vs organisation)
    -- data_principal = individual citizen
    -- data_fiduciary = organisation collecting data
    -- dpo            = Data Protection Officer
    role        VARCHAR(20)     NOT NULL CHECK (role IN ('data_principal', 'data_fiduciary', 'dpo')),

    -- Contact details
    email       VARCHAR(255)    UNIQUE,
    phone       VARCHAR(20)     UNIQUE,

    -- Hashed password (bcrypt). NULL for OAuth/OTP-only users
    password_hash VARCHAR(255),

    -- Full name of the user / organisation name
    full_name   VARCHAR(255)    NOT NULL,

    -- For data_fiduciary: their registered organisation ID (e.g., CIN number)
    org_id      VARCHAR(100),

    -- Account state
    is_active   BOOLEAN         NOT NULL DEFAULT TRUE,
    is_verified BOOLEAN         NOT NULL DEFAULT FALSE,

    -- Timestamps (always store in UTC)
    created_at  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- Index on email for fast lookups during login
CREATE INDEX IF NOT EXISTS idx_auth_users_email ON auth.users (email);

-- Index on phone for OTP-based login
CREATE INDEX IF NOT EXISTS idx_auth_users_phone ON auth.users (phone);

-- Index on role to quickly query all fiduciaries / principals
CREATE INDEX IF NOT EXISTS idx_auth_users_role ON auth.users (role);

-- +goose StatementEnd


-- =============================================================================
-- +goose Down
-- +goose StatementBegin

DROP TABLE IF EXISTS auth.users;

-- +goose StatementEnd
